name: Reusable workflow
on: 
    workflow_call:
        inputs: 
            artifact-name:
                description: 'Name of the artifact to download'
                required: false # if true it will means jobs will require this input and if not found it will give error 
                default: dist
                type: string
        outputs:
          result:
            description: 'Result of the deployment'
            value: ${{ jobs.Deploy.outputs.resultsss }}
              
jobs:
    Deploy:
        outputs:
          resultsss: ${{ steps.set-res.outputs.step-result }}
        runs-on: Ubuntu-latest
        steps:
          - name: Download the artifacts
            uses: actions/download-artifact@v4
            with:
              name: ${{ inputs.artifact-name }}
          - name: Deploy
            run: echo "Deployed to the server" 
          - name: Set result output
            id: set-res
            run: echo "step-result=success">> $GITHUB_OUTPUT