name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Lint:
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.operating-system}}
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix['node-version'] }}
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: depsnode-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install the dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lint the code
        run: npm run lint
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: depsnode-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install the dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test the code
        id: test
        continue-on-error: true # Allow the workflow to continue even if tests fail
        run: npm run test
      - name: Upload test reports
        if: failure() && steps.test.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: test.json
  Build:
    needs: Test
    runs-on: Ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: depsnode-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install the dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build the code
        run: npm run buildx
      - name: Upload the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist

  Deploy:
    needs: Build
    runs-on: Ubuntu-latest
    steps:
      - name: Download the artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Deploy
        run: echo "Deployed to the server"
