name: Deployment
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
            - name: Load cache the dependencies
              id: load-deps
              uses: ./.github/actions/cached-deps
              with:
                caching: 'false'
            - name: output info
              run: echo " Cache used? ${{ steps.load-deps.outputs.used-cache }} "
            - name: Lint the code
              run: npm run lint

    Test:
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
            - name: Load cache the dependencies
              uses: ./.github/actions/cached-deps
            - name: Test the code
              id: test-step
              run: npm run test
            - name: Upload test results
              if: failure() && steps.test-step.outcome == 'failure'
              uses: actions/upload-artifact@v4
              with:
                name: test-results
                path: test.json
    Build:
        needs: Test
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
            - name: Load cache the dependencies
              uses: ./.github/actions/cached-deps
            - name: Build the code
              run: npm run build
            - name: Upload the artifacts
              uses: actions/upload-artifact@v4
              with:
                name: dist-files
                path: dist
    Deploy:
        needs: Build
        uses: ./.github/workflows/reusedeploy.yml
        with:
            artifact_name: dist-files   
    print_deploy_result:
        needs: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Print the deploy result
              run: echo "Deployment result is ${{ needs.Deploy.outputs.result }}"
    information:
        runs-on: ubuntu-latest
        steps:
            - name: Run custom js action
              uses: ./.github/actions/deploy-s3-js
