name: Reusing the deploy part
on: 
    workflow_call:
        inputs:
            artifact_name:
                description: 'Downloading the build artifact'
                required: true
                default: dist
                type: string
jobs:
    Deploy:
       runs-on: ubuntu-latest
       steps:
            - name: Download the artifacts
              uses: actions/download-artifact@v4
              with:
                name: ${{ inputs.artifact_name }}
            - name: Deploy
              id: deploy-step
              uses: ./.github/actions/deploy-s3-js
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              with:
                    bucket: 'customhai' #required
                    bucket-region: 'ap-south-1' #optional
                    dist-folder: './dist' #required
            - name: Output info
              run: |
                   echo "Live url : ${{ steps.deploy-step.outputs.deploy-url }}"