name: Reusing the deploy part
on: 
    workflow_call:
        inputs:
            artifact_name:
                description: 'Downloading the build artifact'
                required: true
                default: dist
                type: string
        outputs:
            result:
                description: "Result of the deployment"
                value: ${{ jobs.Deploy.outputs.resultsss }}

jobs:
    Deploy:
        outputs:
            resultsss: ${{ steps.set-res.outputs.STEP-result }}

        runs-on: ubuntu-latest
        steps:
            - name: Download the artifacts
              uses: actions/download-artifact@v4
              with:
                name: ${{ inputs.artifact_name }}
            - name: Deploy
              uses: ./.github/actions/deploy-s3-js
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              with:
                    bucket: 'my-unique-bucket-name-12345' #required
                    bucket-region: 'us-east-1'
                    dist-folder: './dist' #required
            - name: Display the result
              id: set-res
              run: echo "STEP-result==success ">> $GITHUB_OUTPUT